- name: Install MySQL
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000
  with_items:
  - mysql-server
  - python-mysqldb

- name: Create MySQL database
  mysql_db: name={{ mysql_dbname }} state=present

- name: Create Database User
  mysql_user: > 
    name={{ mysql_user }}
    password={{ mysql_password }}
    priv={{ mysql_dbname }}.*:ALL 
    state=present
  no_log: true