- name: Create download directory
  file:
    path: /usr/local/dist
    state: directory

- name: Download Composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755