- name: Install Zip
  apt: pkg=zip update_cache=yes cache_valid_time=36000

- name: Install PHP and modules
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000
  with_items:
    - php5
    - php5-apcu
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-mcrypt
    - php5-memcached

- name: Copy php.ini
  copy: >
    src=php.ini
    dest=/etc/php5/apache2/php.ini
  notify: restart apache