- name: Install Prerequisites for Certbot
  apt:
    name: software-properties-common
    update_cache: yes
    cache_valid_time: 36000

- name: Add PPA repository for Certbot
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install Apache and Certbot
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 36000
  with_items:
    - apache2
    - python-certbot-apache
    # - libapache2

- name: Enable Apache Rewrite modules
  command: a2enmod rewrite
  notify: restart apache

- name: Enable Apache unique_id and ssl modules
  command: a2enmod unique_id ssl
  notify: restart apache